spring:
  h2:
    console.enabled: true
  datasource:
    url: jdbc:h2:mem:testdb;DATABASE_TO_UPPER=false;
    driverClassName: org.h2.Driver
  jpa:
    defer-datasource-initialization: true
    properties.hibernate.format_sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
